# Generated by Django 5.2.4 on 2025-07-22 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='key',
            options={'permissions': [('generate_key', 'Can generate API key')]},
        ),
    ]
