# Generated by Django 5.2.4 on 2025-07-16 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('code', models.CharField(help_text='Код доски (например, b)', max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Описание доски, которое видят пользователи в её шапке')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('creation', models.DateTimeField(auto_now=True, help_text='Дата и время создания')),
                ('text', models.TextField(help_text='Текст')),
                ('board', models.ForeignKey(help_text='Доска треда', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.board')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('creation', models.DateTimeField(auto_now=True, help_text='Дата и время создания')),
                ('text', models.TextField(help_text='Текст')),
                ('thread', models.ForeignKey(help_text='Тред, к которому пишется комментарий', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.thread')),
            ],
        ),
    ]
