# Generated by Django 5.2.4 on 2025-07-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(default='None', help_text='Заголовок', max_length=20),
        ),
    ]
