# Generated by Django 5.2.4 on 2025-07-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_thread_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='tid',
        ),
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='thread',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
