# Generated by Django 5.2.4 on 2025-07-20 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_comment_cid_remove_thread_tid_comment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Файл', upload_to='')),
                ('comment', models.ForeignKey(help_text='Коммент с файлом.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.comment')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Файл', upload_to='')),
                ('thread', models.ForeignKey(help_text='Тред с файлом', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.thread')),
            ],
        ),
    ]
