# Generated by Django 5.2.4 on 2025-07-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_commentfile_threadfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadfile',
            name='thread',
        ),
        migrations.AddField(
            model_name='thread',
            name='file',
            field=models.FileField(help_text='Файл', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='CommentFile',
        ),
        migrations.DeleteModel(
            name='ThreadFile',
        ),
    ]
