# Generated by Django 5.2.4 on 2025-07-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_remove_threadfile_thread_thread_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(help_text='Файл', null=True, upload_to=''),
        ),
    ]
