# Generated by Django 5.2.4 on 2025-07-20 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_comment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='file',
        ),
        migrations.CreateModel(
            name='CommentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Файл', null=True, upload_to='')),
                ('comment', models.ForeignKey(help_text='Коммент, которому принадлежит файл', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.comment')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Файл', null=True, upload_to='')),
                ('thread', models.ForeignKey(help_text='Тред, которому принадлежит файл', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.thread')),
            ],
        ),
    ]
