# Generated by Django 5.2.4 on 2025-07-22 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_remove_comment_file_remove_thread_file_commentfile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'permissions': [('create_new_threads', 'Can create new threads'), ('comment_threads', 'Can comment threads')]},
        ),
    ]
