# Generated by Django 5.2.4 on 2025-07-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_alter_thread_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'permissions': [('upload_large_files', 'Can upload large files')]},
        ),
    ]
